services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: pharma
      POSTGRES_USER: pharma_user
      POSTGRES_PASSWORD: pharma_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docs/db-schema.sql:/docker-entrypoint-initdb.d/01-schema.sql:ro

volumes:
  pgdata:
